### PR TITLE
Testing/64.2

### PR DESCRIPTION
**Pull request by jmarrec**
Add recipe for using 64.2. Updated the Sha256. I also looking at the ICU source and ensured that the single patch file that I found is no longer needed since the patch has been propagated upstream.

Builds fine on Ubuntu 16.04, haven't tried other platforms.

As for the "why", I wish to use conan-qt  `--with-icu=True`, and found this comment https://github.com/bincrafters/conan-qt/blob/stable/5.12.3/conanfile.py#L68

### CODE REVIEW

**Comment by jmarrec** [comment]
I will need to change the base branch to testing/64.1 once it has been created. cf https://github.com/bincrafters/community/issues/802

**Edit**: Done, changed the base. Will wait for CI to test other platforms.

**Review by Croydon — CHANGES_REQUESTED** [review]
`exports_sources = ["patches/*.patch"]`

needs to get removed

**Comment by jmarrec** [comment]
This ends up globbing nothing IIUC (and is more future proof), but I can remove anyways sure

**Comment by SSE4** [comment]
Windows fails with:
```
icu/64.2@bincrafters/testing: Warning: mappings/cns-11643-1992.cnv claims to be 'CNS-11643-1992'
icu/64.2@bincrafters/testing: Couldn't create the udata mappings/cns-11643-1992.cnv: U_FILE_ACCESS_ERROR
icu/64.2@bincrafters/testing: Error writing "./out/build/icudt64l\mappings/cns-11643-1992.cnv" file for "../../source/data\mappings/cns-11643-1992.ucm" (U_FILE_ACCESS_ERROR)
icu/64.2@bincrafters/testing: make[1]: *** [../data/rules.mk:20: out/build/icudt64l/cns-11643-1992.cnv] Error 4
icu/64.2@bincrafters/testing: make[1]: *** Waiting for unfinished jobs....
icu/64.2@bincrafters/testing: make: *** [Makefile:153: all-recursive] Error 2
```

**Comment by jmarrec** [comment]
@SSE4 Strange, I'm getting a different build error locally, which can be found on an older appveyor log too: https://ci.appveyor.com/project/bincrafters/conan-icu/builds/24698435/job/7jbt66qykj9gq2j8#L477

```
icu/64.2@bincrafters/testing: Spawning Python to generate data/rules.mk...
icu/64.2@bincrafters/testing: Spawning Python to generate test/testdata/rules.mk...
icu/64.2@bincrafters/testing: C:\Python37-x64\python.exe: No module named buildtool
icu/64.2@bincrafters/testing: configure: error: Python failed to run; see above error.
icu/64.2@bincrafters/testing: ../source/runConfigureICU: ./configure failed
icu/64.2@bincrafters/testing: 
icu/64.2@bincrafters/testing: ERROR: Package '6cda8fa4bcebf373f40b874f9409e40fab872e71' build failed
```

Seems like the icu4c/source/data/buildtool/configure script is guilty to use `:` instead of the earlier determined plaftorm-dependent `$PATH_SEPARATOR`.

I found at least two occurrences.

L4331:
```
-as_dummy="$PATH:/usr/local/bin:/usr/bin"
+as_dummy="$PATH$PATH_SEPARATOR/usr/local/bin$PATH_SEPARATOR/usr/bin"
```

L9141:
```
-PYTHONPATH="$srcdir/test/testdata:$srcdir/data" $PYTHON -m buildtool \
icu4c/source/configure  
+PYTHONPATH="$srcdir/test/testdata$PATH_SEPARATOR$srcdir/data" $PYTHON -m buildtool \
icu4c/source/configure
```

**Comment by SSE4** [comment]
@jmarrec I think this particular error was fixed in https://github.com/bincrafters/conan-icu/pull/18/commits/d0b1f832f212cabf6f0c1e8c9d9b2a02dcbf1ccc
could you try to update?

**Comment by jmarrec** [comment]
@SSE4 I already tried with the tip of the branch on this PR 0c0a41823b8890717aae38577fc9dd22afa01bb3

**Comment by jmarrec** [comment]
No wait a minute, I forgot to fetch and thought I was up to date. I'll try again sorry.

**Edit**: yes it fixed this specific build error, sorry about the confusion

**Pull request merged**
